spring:
  application:
    name: eureka-server

server:
  port: 9099

  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
  service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

