spring:
  application:
    name: kyc-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  datasource:
    url:  jdbc:postgresql://postgres:5432/kycdb
    password: KyC@2025! 
    username: kycapp 
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      format_sql: true
      ddl-auto: update
  logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8081
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include:  health
  endpoint:
    health:
      show-details: always
  server:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:9099/eureka/eureka
  instance:
    prefer-ip-address: true


rabbitmq:
  queue:
    name: email-queue
  routing:
    key:  email_key
  exchange: 
    name: email_exchange