spring:
  application:
    name: eureka-registry

server:
  port: 9099
  address: 0.0.0.0
  servlet:
    context-path: /eureka

  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

